// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package main

import (
	"context"
	"sync"

	"github.com/google/go-containerregistry/pkg/name"
	v1 "github.com/google/go-containerregistry/pkg/v1"
	"github.com/google/go-containerregistry/pkg/v1/mutate"
)

// Ensure, that mockNixBuilderClient does implement nixBuilderClient.
// If this is not the case, regenerate this file with moq.
var _ nixBuilderClient = &mockNixBuilderClient{}

// mockNixBuilderClient is a mock implementation of nixBuilderClient.
//
//	func TestSomethingThatUsesnixBuilderClient(t *testing.T) {
//
//		// make and configure a mocked nixBuilderClient
//		mockednixBuilderClient := &mockNixBuilderClient{
//			BuildPlatformImageFunc: func(contextMoqParam context.Context, s string, reference name.Reference, platform *v1.Platform, imageOptionMoqParams ...imageOption) (string, error) {
//				panic("mock out the BuildPlatformImage method")
//			},
//		}
//
//		// use mockednixBuilderClient in code that requires nixBuilderClient
//		// and then make assertions.
//
//	}
type mockNixBuilderClient struct {
	// BuildPlatformImageFunc mocks the BuildPlatformImage method.
	BuildPlatformImageFunc func(contextMoqParam context.Context, s string, reference name.Reference, platform *v1.Platform, imageOptionMoqParams ...imageOption) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// BuildPlatformImage holds details about calls to the BuildPlatformImage method.
		BuildPlatformImage []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
			// Reference is the reference argument value.
			Reference name.Reference
			// Platform is the platform argument value.
			Platform *v1.Platform
			// ImageOptionMoqParams is the imageOptionMoqParams argument value.
			ImageOptionMoqParams []imageOption
		}
	}
	lockBuildPlatformImage sync.RWMutex
}

// BuildPlatformImage calls BuildPlatformImageFunc.
func (mock *mockNixBuilderClient) BuildPlatformImage(contextMoqParam context.Context, s string, reference name.Reference, platform *v1.Platform, imageOptionMoqParams ...imageOption) (string, error) {
	callInfo := struct {
		ContextMoqParam      context.Context
		S                    string
		Reference            name.Reference
		Platform             *v1.Platform
		ImageOptionMoqParams []imageOption
	}{
		ContextMoqParam:      contextMoqParam,
		S:                    s,
		Reference:            reference,
		Platform:             platform,
		ImageOptionMoqParams: imageOptionMoqParams,
	}
	mock.lockBuildPlatformImage.Lock()
	mock.calls.BuildPlatformImage = append(mock.calls.BuildPlatformImage, callInfo)
	mock.lockBuildPlatformImage.Unlock()
	if mock.BuildPlatformImageFunc == nil {
		var (
			sOut   string
			errOut error
		)
		return sOut, errOut
	}
	return mock.BuildPlatformImageFunc(contextMoqParam, s, reference, platform, imageOptionMoqParams...)
}

// BuildPlatformImageCalls gets all the calls that were made to BuildPlatformImage.
// Check the length with:
//
//	len(mockednixBuilderClient.BuildPlatformImageCalls())
func (mock *mockNixBuilderClient) BuildPlatformImageCalls() []struct {
	ContextMoqParam      context.Context
	S                    string
	Reference            name.Reference
	Platform             *v1.Platform
	ImageOptionMoqParams []imageOption
} {
	var calls []struct {
		ContextMoqParam      context.Context
		S                    string
		Reference            name.Reference
		Platform             *v1.Platform
		ImageOptionMoqParams []imageOption
	}
	mock.lockBuildPlatformImage.RLock()
	calls = mock.calls.BuildPlatformImage
	mock.lockBuildPlatformImage.RUnlock()
	return calls
}

// Ensure, that mockContainerBuilderClient does implement containerBuilderClient.
// If this is not the case, regenerate this file with moq.
var _ containerBuilderClient = &mockContainerBuilderClient{}

// mockContainerBuilderClient is a mock implementation of containerBuilderClient.
//
//	func TestSomethingThatUsescontainerBuilderClient(t *testing.T) {
//
//		// make and configure a mocked containerBuilderClient
//		mockedcontainerBuilderClient := &mockContainerBuilderClient{
//			CheckPushPermissionFunc: func(reference name.Reference) error {
//				panic("mock out the CheckPushPermission method")
//			},
//			PushImageFunc: func(reference name.Reference, s string) error {
//				panic("mock out the PushImage method")
//			},
//			PushManifestFunc: func(reference name.Reference, indexAddendums []mutate.IndexAddendum) error {
//				panic("mock out the PushManifest method")
//			},
//			PushPlatformImageFunc: func(reference name.Reference, platform *v1.Platform, s string) (mutate.IndexAddendum, error) {
//				panic("mock out the PushPlatformImage method")
//			},
//		}
//
//		// use mockedcontainerBuilderClient in code that requires containerBuilderClient
//		// and then make assertions.
//
//	}
type mockContainerBuilderClient struct {
	// CheckPushPermissionFunc mocks the CheckPushPermission method.
	CheckPushPermissionFunc func(reference name.Reference) error

	// PushImageFunc mocks the PushImage method.
	PushImageFunc func(reference name.Reference, s string) error

	// PushManifestFunc mocks the PushManifest method.
	PushManifestFunc func(reference name.Reference, indexAddendums []mutate.IndexAddendum) error

	// PushPlatformImageFunc mocks the PushPlatformImage method.
	PushPlatformImageFunc func(reference name.Reference, platform *v1.Platform, s string) (mutate.IndexAddendum, error)

	// calls tracks calls to the methods.
	calls struct {
		// CheckPushPermission holds details about calls to the CheckPushPermission method.
		CheckPushPermission []struct {
			// Reference is the reference argument value.
			Reference name.Reference
		}
		// PushImage holds details about calls to the PushImage method.
		PushImage []struct {
			// Reference is the reference argument value.
			Reference name.Reference
			// S is the s argument value.
			S string
		}
		// PushManifest holds details about calls to the PushManifest method.
		PushManifest []struct {
			// Reference is the reference argument value.
			Reference name.Reference
			// IndexAddendums is the indexAddendums argument value.
			IndexAddendums []mutate.IndexAddendum
		}
		// PushPlatformImage holds details about calls to the PushPlatformImage method.
		PushPlatformImage []struct {
			// Reference is the reference argument value.
			Reference name.Reference
			// Platform is the platform argument value.
			Platform *v1.Platform
			// S is the s argument value.
			S string
		}
	}
	lockCheckPushPermission sync.RWMutex
	lockPushImage           sync.RWMutex
	lockPushManifest        sync.RWMutex
	lockPushPlatformImage   sync.RWMutex
}

// CheckPushPermission calls CheckPushPermissionFunc.
func (mock *mockContainerBuilderClient) CheckPushPermission(reference name.Reference) error {
	callInfo := struct {
		Reference name.Reference
	}{
		Reference: reference,
	}
	mock.lockCheckPushPermission.Lock()
	mock.calls.CheckPushPermission = append(mock.calls.CheckPushPermission, callInfo)
	mock.lockCheckPushPermission.Unlock()
	if mock.CheckPushPermissionFunc == nil {
		var errOut error
		return errOut
	}
	return mock.CheckPushPermissionFunc(reference)
}

// CheckPushPermissionCalls gets all the calls that were made to CheckPushPermission.
// Check the length with:
//
//	len(mockedcontainerBuilderClient.CheckPushPermissionCalls())
func (mock *mockContainerBuilderClient) CheckPushPermissionCalls() []struct {
	Reference name.Reference
} {
	var calls []struct {
		Reference name.Reference
	}
	mock.lockCheckPushPermission.RLock()
	calls = mock.calls.CheckPushPermission
	mock.lockCheckPushPermission.RUnlock()
	return calls
}

// PushImage calls PushImageFunc.
func (mock *mockContainerBuilderClient) PushImage(reference name.Reference, s string) error {
	callInfo := struct {
		Reference name.Reference
		S         string
	}{
		Reference: reference,
		S:         s,
	}
	mock.lockPushImage.Lock()
	mock.calls.PushImage = append(mock.calls.PushImage, callInfo)
	mock.lockPushImage.Unlock()
	if mock.PushImageFunc == nil {
		var errOut error
		return errOut
	}
	return mock.PushImageFunc(reference, s)
}

// PushImageCalls gets all the calls that were made to PushImage.
// Check the length with:
//
//	len(mockedcontainerBuilderClient.PushImageCalls())
func (mock *mockContainerBuilderClient) PushImageCalls() []struct {
	Reference name.Reference
	S         string
} {
	var calls []struct {
		Reference name.Reference
		S         string
	}
	mock.lockPushImage.RLock()
	calls = mock.calls.PushImage
	mock.lockPushImage.RUnlock()
	return calls
}

// PushManifest calls PushManifestFunc.
func (mock *mockContainerBuilderClient) PushManifest(reference name.Reference, indexAddendums []mutate.IndexAddendum) error {
	callInfo := struct {
		Reference      name.Reference
		IndexAddendums []mutate.IndexAddendum
	}{
		Reference:      reference,
		IndexAddendums: indexAddendums,
	}
	mock.lockPushManifest.Lock()
	mock.calls.PushManifest = append(mock.calls.PushManifest, callInfo)
	mock.lockPushManifest.Unlock()
	if mock.PushManifestFunc == nil {
		var errOut error
		return errOut
	}
	return mock.PushManifestFunc(reference, indexAddendums)
}

// PushManifestCalls gets all the calls that were made to PushManifest.
// Check the length with:
//
//	len(mockedcontainerBuilderClient.PushManifestCalls())
func (mock *mockContainerBuilderClient) PushManifestCalls() []struct {
	Reference      name.Reference
	IndexAddendums []mutate.IndexAddendum
} {
	var calls []struct {
		Reference      name.Reference
		IndexAddendums []mutate.IndexAddendum
	}
	mock.lockPushManifest.RLock()
	calls = mock.calls.PushManifest
	mock.lockPushManifest.RUnlock()
	return calls
}

// PushPlatformImage calls PushPlatformImageFunc.
func (mock *mockContainerBuilderClient) PushPlatformImage(reference name.Reference, platform *v1.Platform, s string) (mutate.IndexAddendum, error) {
	callInfo := struct {
		Reference name.Reference
		Platform  *v1.Platform
		S         string
	}{
		Reference: reference,
		Platform:  platform,
		S:         s,
	}
	mock.lockPushPlatformImage.Lock()
	mock.calls.PushPlatformImage = append(mock.calls.PushPlatformImage, callInfo)
	mock.lockPushPlatformImage.Unlock()
	if mock.PushPlatformImageFunc == nil {
		var (
			indexAddendumOut mutate.IndexAddendum
			errOut           error
		)
		return indexAddendumOut, errOut
	}
	return mock.PushPlatformImageFunc(reference, platform, s)
}

// PushPlatformImageCalls gets all the calls that were made to PushPlatformImage.
// Check the length with:
//
//	len(mockedcontainerBuilderClient.PushPlatformImageCalls())
func (mock *mockContainerBuilderClient) PushPlatformImageCalls() []struct {
	Reference name.Reference
	Platform  *v1.Platform
	S         string
} {
	var calls []struct {
		Reference name.Reference
		Platform  *v1.Platform
		S         string
	}
	mock.lockPushPlatformImage.RLock()
	calls = mock.calls.PushPlatformImage
	mock.lockPushPlatformImage.RUnlock()
	return calls
}
